# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - my_network
    restart: unless-stopped

  bot:
    build: .
    volumes:
      - .:/app
    command: ["python", "app/api/tg_bot.py"]
    networks:
      - my_network
    env_file:
      - .env
    restart: unless-stopped

networks:
  my_network: